root: true
env:
  browser: true
  es2021: true
extends:
  - airbnb
  - airbnb-typescript
  - airbnb/hooks
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - prettier
plugins:
  - '@typescript-eslint'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
  project: ./tsconfig.eslint.json
rules:
  no-alert: off
  '@typescript-eslint/lines-between-class-members': off
  max-classes-per-file: off
  class-methods-use-this: off
  '@typescript-eslint/explicit-member-accessibility':
    - error
    - accessibility: no-public
  no-underscore-dangle:
    - error
    - allowAfterThis: true
  '@typescript-eslint/naming-convention':
    - error
    - selector: variable
      format:
        - camelCase
        - UPPER_CASE
    - selector: classProperty
      format:
        - camelCase
        - UPPER_CASE
      leadingUnderscore: allow
    - selector: typeLike
      format:
        - PascalCase
    - selector: parameter
      format:
        - camelCase
      leadingUnderscore: allow
    - selector: objectLiteralProperty
      format:
        - camelCase
        - snake_case
    - selector: enumMember
      format:
        - UPPER_CASE
    - selector: default
      format:
        - camelCase
    - selector: function
      format:
        - strictCamelCase
        - PascalCase
  react/react-in-jsx-scope: off
