name: CI

on:
  push:
    branches:
      - '**'

jobs:
  testsuite:
    runs-on: ubuntu-latest

    steps:
      - name: install npm packages
        run: npm i

      - name: check prettier
        run: npx prettier --loglevel=error --check ./src

      - name: check eslint
        run: npx eslint ./src

      - name: check stylelint
        run: npx stylelint ./src
